# ===============================
# CONFIGURAÇÕES DO SERVIDOR
# ===============================
server.port=8080
spring.application.name=financer-backend

# ===============================
# CONFIGURAÇÕES DO POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/financer_db
spring.datasource.username=postgres
spring.datasource.password=fincker1001
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO HIBERNATE/JPA
# ===============================
# O 'update' faz o Spring criar as tabelas automaticamente baseado nas nossas classes Model
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true